### PR TITLE
In 986 - merge mappings repo with main repo

### PR DESCRIPTION
**Pull request by jamesrwarren**
## Purpose

Merge mapping a base repo to make changes easier for developers

## Approach

Created some private test repos:

Added file to orig repo and committed and pushed to main
Added file to to_merge repo and committed and pushed to main
Added to_merge repo as remote of orig repo
Brought in the commit history and files with a merge
Added file2 to orig repo and committed and pushed to main
Added file3 to to_merge repo and committed and pushed to main
Checked out new_branch on orig
Brought in the commit history and files with a merge from to_merge repo again
Added file3 to orig repo and committed and pushed to new_branch
Approved branch and merged to main

Checked git history. Looked good. Had all the commits and files we expected.

Did same process with main repo but then moved everything around so it works properly. 

Kept pushes to S3 of the zip but only when we merge so we have a versioned list of updates as backup

Otherwise I decided that people should run the container to generate the files when doing a PR rather than it happening in the container. This will keep us from forgetting as it will use the json files in repo when you commit.

## Learning

Merging repos... 

## Checklist

* [x] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] I have updated documentation where relevant
* [ ] I have added tests to prove my work
* [ ] The product team have tested these changes

### CODE REVIEW

**Comment by townxelliot** [comment]
Presumably we don't need the option to sync the mappings from the repo, as we'd always use the version in our clone? Is the intention to remove that stuff and add a step to regenerate the mappings locally if required?

**Comment by jamesrwarren** [comment]
> Presumably we don't need the option to sync the mappings from the repo, as we'd always use the version in our clone? Is the intention to remove that stuff and add a step to regenerate the mappings locally if required?
> 
> I notice you commented on this. I'd say we should generate the mapping JSON from the local spreadsheets when we run migrate.sh, but only if a spreadsheet has changed since the last time the JSON was generated, maybe? I'd like to be confident that I'm not running with an out-of-date version of the JSON mappings, e.g. if I'm editing my local spreadsheets to change a mapping, I don't want to have to remember to manually update the JSON mappings before running migrate.sh; I'd rather either it was done automatically, or there's a strong reminder to update them in the migrate.sh script.

I don't know if I want to remove the sync out of the migrate.sh. I think whilst working on things you might make some changes then decide you want to scrap them so can resync from mapping. This is helpful if you're not super smart with commits.

As for your other point of making it regen the files as part of migrate.sh, that seems like a good plan... let me think if theres an easy way to do that

**Comment by townxelliot** [comment]
> I don't know if I want to remove the sync out of the migrate.sh. I think whilst working on things you might make some changes then decide you want to scrap them so can resync from mapping. This is helpful if you're not super smart with commits.
> 
> As for your other point of making it regen the files as part of migrate.sh, that seems like a good plan... let me think if theres an easy way to do that

If you've messed up the mapping, that's likely to be because you've edited the spreadsheet locally. In that case, sync'ing from S3 isn't going to help you, as your spreadsheet will be wrong. You're going to have to work out how to get the good version of the spreadsheet by fixing your commits, then regenerate the mappings from that.

**Review by devkokov — DISMISSED** [review]
I'd agree with Elliot. There's less need for a sync option with merging the repos, but equally there's no harm in having the option 🤷

**Comment by jamesrwarren** [comment]
I'll take it out of the migrate.sh but leave it as a script you can use if needed. Adding the conditional build into the repo.. now... Can't guarantee how it will work between downloads etc... it's doing a sha of the spreadsheet folder and keeping a record of it

**Review by devkokov — APPROVED** [review]

**Pull request merged**
