### PR TITLE
IN-1061 Map missing foreign keys for reporting tables

### PR DESCRIPTION
**Pull request by townxelliot**
## Purpose

[IN-1061](https://opgtransform.atlassian.net/browse/IN-1061)

## Approach

* Fix interpretation of is_complete column in mapping spreadsheets so it can be set correctly for reporting fks
* Where a mapping doesn't directly map a column from casrec to Sirius, ensure that the transform can still get a table name by falling back to the table definition
* Other general clean up where I spotted issues (unused files, unnecessary files, unnecessary disk IO)

## Learning

n/a

## Checklist

* [X] I have performed a self-review of my own code
* [ ] I have done an adhoc run against preprod (only needed for high complexity PRs)
* [X] I have added relevant logging with appropriate levels to my code
* [X] I have updated documentation where relevant
* [X] I have added tests to prove my work
* [ ] The product team have tested these changes

### CODE REVIEW

**Review by jackgoodby — DISMISSED** [review]

**Comment by townxelliot** [comment]
Decided to take IN-1081 out of this as it was making things too complicated.

**Review by jackgoodby — DISMISSED** [review]

**Comment by townxelliot** [comment]
@jackgoodby would you mind ticking again please? I found a small change to do something a slightly better way and couldn't resist doing it.

**Review by jackgoodby — DISMISSED** [review]

**Comment by townxelliot** [comment]
Should be merged after https://github.com/ministryofjustice/opg-data-casrec-migration/pull/507 (and will need some conflict resolution).

**Comment by devkokov** [comment]
> 

#507 has now been merged in @townxelliot

**Comment by townxelliot** [comment]
@jackgoodby Sorry, had to manually fix some conflicts with master when merging, which once again invalidated your review. Could you please re-tick again? I'll get this merged as soon as the tests pass. Thanks.

**Review by jackgoodby — APPROVED** [review]

**Pull request merged**
