### PR TITLE
IN-1198 Add script to update PENDING reports reviewstatus (PM11 integrated into automation)

### PR DESCRIPTION
**Pull request by townxelliot**
## Purpose

[IN-1198](https://opgtransform.atlassian.net/browse/IN-1198)

## Approach

SQL, innit

## Learning

n/a

## Checklist

* [ ] I have performed a self-review of my own code
* [ ] I have done an adhoc run against preprod (only needed for high complexity PRs)
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] I have updated documentation where relevant
* [ ] I have added tests to prove my work
* [ ] The product team have tested these changes

### CODE REVIEW

**Comment by townxelliot** [comment]
@devkokov I clarified with @farzan1990 that we should be looking for the most-recent row in the account table with Rev Stat = 'S', then join that on case to the annual_report_logs. Where this produces rows, set reviewstatus to 'STAFF_PRESELECTED'. I think what I've got here is correct, given that spec, if you wouldn't mind checking it over again for me.

**Comment by devkokov** [comment]
@townxelliot the PR looks good, but I'm still unsure about the business logic. My understanding is that the latest report in `account` is not guaranteed to be a Pending report. Is Farzan saying that the Pending report in Sirius should be marked "STAFF_PRESELECTED" if the previous report (which is latest in `account`) has RevStat=S? I think there should be another condition to ensure that the Pending report in Sirius is the exact same report that has the RevStat=S in Casrec.

**Comment by devkokov** [comment]
Oh, and even if the latest report in "account" was Pending, it is not guaranteed to be Pending in Sirius anymore, as it may have transitioned to Due/Overdue etc.

**Comment by townxelliot** [comment]
> @townxelliot the PR looks good, but I'm still unsure about the business logic. My understanding is that the latest report in `account` is not guaranteed to be a Pending report. Is Farzan saying that the Pending report in Sirius should be marked "STAFF_PRESELECTED" if the previous report (which is latest in `account`) has RevStat=S? I think there should be another condition to ensure that the Pending report in Sirius is the exact same report that has the RevStat=S in Casrec.

Bear in mind that most of the PENDING reports we migrated were from the pat table. For those, we have (unfortunately) no way to track them back to the pat table in casrec, as I used non-standard SQL to generate them and bypassed the logic which records the casrec row ID.

**Review by jamesrwarren — DISMISSED** [review]

**Review by jamesrwarren — DISMISSED** [review]

**Comment by townxelliot** [comment]
Folder now moved. I also made additional changes to the post-migration script runner to help me do this. I also moved the PM10 folder from scripts into the correct location.

**Review by jamesrwarren — APPROVED** [review]

**Pull request merged**
